name: "PR Preview Commenter"
description: "Posts or updates a comment in a PR with a link to the preview environment"
author: "Alex Parra"

inputs:
  github_token:
    description: "GitHub token for authentication"
    required: true
  preview_url:
    description: "Preview environment message"
    required: false


runs:
  using: "node20"
  main: "dist/index.js"

branding:
  icon: "message-square"
  color: "blue"