name: "PR Preview Commenter"
description: "Posts or updates a comment in a PR with a link to the preview environment"
author: "Alex Parra"

inputs:
  github_token:
    description: "GitHub token for authentication"
    required: true
  message:
    description: "Message to be posted in the comment"
    required: false
  repo_name:
    description: "Repository name"
    required: false


runs:
  using: "node20"
  main: "dist/index.js"

branding:
  icon: "message-square"
  color: "blue"