name: "PR Preview Commenter"
description: "Posts or updates a comment in a PR with a link to the preview environment"
author: "Alex Parra"

inputs:
  github_token:
    description: "GitHub token for authentication"
    required: true
  repo_owner:
    description: "Repository owner"
    required: false
  repo_name:
    description: "Repository name"
    required: true
  pr_number:
    description: "Pull request number"
    required: true
  pr_message:
    description: "Preview environment message"
    required: true
  commit_sha:
    description: "Commit SHA"
    required: true

runs:
  using: "node20"
  main: "dist/index.js"

branding:
  icon: "message-square"
  color: "blue"